# Copyright 2025 Patryk Rostkowski
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: '3'

tasks:
  kind:create:
    desc: "Create kind cluster for controlplane development"
    cmds:
      - kind create cluster --name controlplane

  kind:delete:
    desc: "Delete kind cluster used for controlplane development"
    cmds:
      - kind delete cluster --name controlplane

  kind:load-image:
    desc: "Load locally built operator image into kind cluster"
    deps:
      - dev:build
    cmds:
      - kind load docker-image patrostkowski/controlplane-operator:latest --name controlplane

  docs:
    desc: "Serve controlplane MkDocs from ./docs/"
    cmds:
      - docker run --rm -it -p 8000:8000 -v ${PWD}/docs:/docs squidfunk/mkdocs-material serve -f /docs/mkdocs.yml -a 0.0.0.0:8000

  dev:setup:
    desc: Validate local dev environment and install git hooks
    cmds:
      - |
        set -euo pipefail
        require() {
          local bin="$1"
          command -v "$bin" >/dev/null 2>&1 || {
            echo "Missing required binary: $bin" >&2
            exit 1
          }
          which $bin
        }
        require go
        require docker
        require kubectl
        require helm
        require kind
        require pre-commit
        require golangci-lint
        require addlicense
        require controller-gen
        pre-commit install

  dev:test:
    desc: "Run unit tests"
    cmds:
      - go test ./pkg/... -v

  dev:lint:
    desc: "Run golangci-lint"
    cmds:
      - golangci-lint run ./...

  dev:e2e:
    desc: "Run E2E tests. Invoke with extra flags: `task dev:e2e -- -args --no-cleanup --stage=run`"
    cmds:
      - go test ./e2e -v -count=1 -p 1 {{.CLI_ARGS}}

  dev:codegen:
    desc: "Run all code generation scripts (client + CRDs) inside hack/"
    cmds:
      - bash hack/update-codegen.sh
      - bash hack/update-crds.sh
      - addlicense -c "Patryk Rostkowski" -l apache -y 2025 .
  
  dev:install:
    desc: "Install controlplane CRDs into current kube context"
    cmds:
      - helm upgrade --install cert-manager "oci://quay.io/jetstack/charts/cert-manager"                                       
        --namespace cert-manager
        --create-namespace
        --set crds.enabled=true
      - kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.15.3/config/manifests/metallb-native.yaml
      - kubectl apply -f config/crd/

  dev:run:
    desc: "Run the controlplane operator locally (for development)"
    dir: cmd/controlplane-operator
    cmds:
      - go run main.go

  dev:docker-build:
    desc: "Build controlplane operator Docker image"
    cmds:
      - docker build . -t patrostkowski/controlplane-operator:latest

  dev:build:
    cmds:
      - go build -o bin/controlplane-operator ./cmd/controlplane-operator/

  dev:build-tesseractl:
    cmds:
      - go build -o bin/tesseractl ./cmd/tesseractl/

  dev:build-all:
    deps:
      - dev:build
      - dev:build-tesseractl
