# Copyright 2025 Patryk Rostkowski
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: '3'

tasks:
  kind:create:
    desc: "Create kind cluster for controlplane development"
    cmds:
      - kind create cluster --name controlplane

  kind:delete:
    desc: "Delete kind cluster used for controlplane development"
    cmds:
      - kind delete cluster --name controlplane

  kind:load-image:
    desc: "Load locally built operator image into kind cluster"
    deps:
      - dev:build
    cmds:
      - kind load docker-image patrostkowski/controlplane-operator:latest --name controlplane


  docs:
    desc: "Serve controlplane MkDocs from ./docs/"
    cmds:
      - docker run --rm -it -p 8000:8000 -v ${PWD}/docs:/docs squidfunk/mkdocs-material serve -f /docs/mkdocs.yml -a 0.0.0.0:8000

  dev:test:
    desc: "Run unit tests"
    cmds:
      - go test ./pkg/... -v

  dev:codegen:
    desc: "Run all code generation scripts (client + CRDs) inside hack/"
    cmds:
      - addlicense -c "Patryk Rostkowski" -l apache -y 2025 .
      - bash hack/update-codegen.sh
      - bash hack/update-crds.sh
  
  dev:install:
    desc: "Install controlplane CRDs into current kube context"
    cmds:
      - helm upgrade --install cert-manager "oci://quay.io/jetstack/charts/cert-manager"                                       
        --namespace cert-manager
        --create-namespace
        --set crds.enabled=true
      - kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.15.3/config/manifests/metallb-native.yaml
      - kubectl apply -f config/crd/
      - kubectl create ns mcp || true
      - kubectl apply -f ./example/mcp.yaml

  dev:run:
    desc: "Run the controlplane operator locally (for development)"
    dir: cmd/controlplane-operator
    cmds:
      - go run main.go

  dev:build:
    desc: "Build controlplane operator Docker image"
    cmds:
      - docker build . -t patrostkowski/controlplane-operator:latest

  dev:build-tesseractd:
    cmds:
      - go build -o bin/tesseractd ./cmd/tesseractd/

  dev:build-tesseractl:
    cmds:
      - go build -o bin/tesseractl ./cmd/tesseractl/

  os:builder:
    desc: Build MCPos builder image
    dir: ./os
    cmds:
      - docker build -t mcpos-builder -f Dockerfile .

  os:fetch-binaries:
    desc: Fetch kubelet/containerd/etc into rootfs using mcpos-builder
    deps:
      - os:builder
    cmds:
      - >
        docker run --rm
        -v "$(pwd)/os:/workspace/os"
        mcpos-builder
        bash -lc "cd /workspace/os && ./scripts/fetch-binaries.sh && ./scripts/fetch-glibc.sh"

  os:build-kernel:
    desc: Build MCPos kernel using mcpos-builder
    deps:
      - os:builder
    cmds:
      - >
        docker run --rm
        -v "$(pwd)/os:/workspace/os"
        mcpos-builder
        bash -lc "cd /workspace/os && ./scripts/build-kernel.sh"

  os:build-initramfs:
    desc: Build MCPos initramfs using mcpos-builder
    deps:
      - os:builder
    cmds:
      - >
        docker run --rm
        -v "$(pwd)/os:/workspace/os"
        mcpos-builder
        bash -lc "cd /workspace/os && ./scripts/build-initramfs.sh"

  os:run-qemu:
    desc: "Run MCPos kernel + initramfs in QEMU (inside mcpos-builder)"
    deps:
      - os:builder
      - os:build-kernel
      - os:build-initramfs
    cmds:
      - >
        docker run --rm -it
        -v "$(pwd)/os:/workspace/os"
        mcpos-builder
        bash -lc "cd /workspace/os && ./scripts/run-qemu.sh"

  os:build:
    desc: Build MCPos kernel + rootfs (inside mcpos-builder)
    deps:
      - os:fetch-binaries
      - os:build-kernel
      - os:build-initramfs
