// Copyright 2025 Patryk Rostkowski
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: agent/v1alpha1/agent.proto

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusCode int32

const (
	StatusCode_STATUS_CODE_UNSPECIFIED StatusCode = 0
	StatusCode_STATUS_CODE_OK          StatusCode = 1
	StatusCode_STATUS_CODE_NOK         StatusCode = 2
)

// Enum value maps for StatusCode.
var (
	StatusCode_name = map[int32]string{
		0: "STATUS_CODE_UNSPECIFIED",
		1: "STATUS_CODE_OK",
		2: "STATUS_CODE_NOK",
	}
	StatusCode_value = map[string]int32{
		"STATUS_CODE_UNSPECIFIED": 0,
		"STATUS_CODE_OK":          1,
		"STATUS_CODE_NOK":         2,
	}
)

func (x StatusCode) Enum() *StatusCode {
	p := new(StatusCode)
	*p = x
	return p
}

func (x StatusCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusCode) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_v1alpha1_agent_proto_enumTypes[0].Descriptor()
}

func (StatusCode) Type() protoreflect.EnumType {
	return &file_agent_v1alpha1_agent_proto_enumTypes[0]
}

func (x StatusCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusCode.Descriptor instead.
func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return file_agent_v1alpha1_agent_proto_rawDescGZIP(), []int{0}
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_agent_v1alpha1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1alpha1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1alpha1_agent_proto_rawDescGZIP(), []int{0}
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          StatusCode             `protobuf:"varint,1,opt,name=code,proto3,enum=agent.v1alpha1.StatusCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Kubelet       *ComponentStatus       `protobuf:"bytes,4,opt,name=kubelet,proto3" json:"kubelet,omitempty"`
	Containerd    *ComponentStatus       `protobuf:"bytes,5,opt,name=containerd,proto3" json:"containerd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_agent_v1alpha1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1alpha1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1alpha1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *StatusResponse) GetCode() StatusCode {
	if x != nil {
		return x.Code
	}
	return StatusCode_STATUS_CODE_UNSPECIFIED
}

func (x *StatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StatusResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *StatusResponse) GetKubelet() *ComponentStatus {
	if x != nil {
		return x.Kubelet
	}
	return nil
}

func (x *StatusResponse) GetContainerd() *ComponentStatus {
	if x != nil {
		return x.Containerd
	}
	return nil
}

type ComponentStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComponentStatus) Reset() {
	*x = ComponentStatus{}
	mi := &file_agent_v1alpha1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentStatus) ProtoMessage() {}

func (x *ComponentStatus) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1alpha1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentStatus.ProtoReflect.Descriptor instead.
func (*ComponentStatus) Descriptor() ([]byte, []int) {
	return file_agent_v1alpha1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *ComponentStatus) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *ComponentStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ComponentStatus) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type JoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoint      string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_agent_v1alpha1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1alpha1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1alpha1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *JoinRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *JoinRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type JoinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          StatusCode             `protobuf:"varint,1,opt,name=code,proto3,enum=agent.v1alpha1.StatusCode" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinResponse) Reset() {
	*x = JoinResponse{}
	mi := &file_agent_v1alpha1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResponse) ProtoMessage() {}

func (x *JoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1alpha1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResponse.ProtoReflect.Descriptor instead.
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1alpha1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *JoinResponse) GetCode() StatusCode {
	if x != nil {
		return x.Code
	}
	return StatusCode_STATUS_CODE_UNSPECIFIED
}

var File_agent_v1alpha1_agent_proto protoreflect.FileDescriptor

const file_agent_v1alpha1_agent_proto_rawDesc = "" +
	"\n" +
	"\x1aagent/v1alpha1/agent.proto\x12\x0eagent.v1alpha1\"\x0f\n" +
	"\rStatusRequest\"\xf4\x01\n" +
	"\x0eStatusResponse\x12.\n" +
	"\x04code\x18\x01 \x01(\x0e2\x1a.agent.v1alpha1.StatusCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x129\n" +
	"\akubelet\x18\x04 \x01(\v2\x1f.agent.v1alpha1.ComponentStatusR\akubelet\x12?\n" +
	"\n" +
	"containerd\x18\x05 \x01(\v2\x1f.agent.v1alpha1.ComponentStatusR\n" +
	"containerd\"_\n" +
	"\x0fComponentStatus\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"?\n" +
	"\vJoinRequest\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\">\n" +
	"\fJoinResponse\x12.\n" +
	"\x04code\x18\x01 \x01(\x0e2\x1a.agent.v1alpha1.StatusCodeR\x04code*R\n" +
	"\n" +
	"StatusCode\x12\x1b\n" +
	"\x17STATUS_CODE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSTATUS_CODE_OK\x10\x01\x12\x13\n" +
	"\x0fSTATUS_CODE_NOK\x10\x022\x9a\x01\n" +
	"\fAgentService\x12G\n" +
	"\x06Status\x12\x1d.agent.v1alpha1.StatusRequest\x1a\x1e.agent.v1alpha1.StatusResponse\x12A\n" +
	"\x04Join\x12\x1b.agent.v1alpha1.JoinRequest\x1a\x1c.agent.v1alpha1.JoinResponseBNZLgithub.com/patrostkowski/controlplane-operator/proto/agent/v1alpha1;v1alpha1b\x06proto3"

var (
	file_agent_v1alpha1_agent_proto_rawDescOnce sync.Once
	file_agent_v1alpha1_agent_proto_rawDescData []byte
)

func file_agent_v1alpha1_agent_proto_rawDescGZIP() []byte {
	file_agent_v1alpha1_agent_proto_rawDescOnce.Do(func() {
		file_agent_v1alpha1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_v1alpha1_agent_proto_rawDesc), len(file_agent_v1alpha1_agent_proto_rawDesc)))
	})
	return file_agent_v1alpha1_agent_proto_rawDescData
}

var file_agent_v1alpha1_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_agent_v1alpha1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_agent_v1alpha1_agent_proto_goTypes = []any{
	(StatusCode)(0),         // 0: agent.v1alpha1.StatusCode
	(*StatusRequest)(nil),   // 1: agent.v1alpha1.StatusRequest
	(*StatusResponse)(nil),  // 2: agent.v1alpha1.StatusResponse
	(*ComponentStatus)(nil), // 3: agent.v1alpha1.ComponentStatus
	(*JoinRequest)(nil),     // 4: agent.v1alpha1.JoinRequest
	(*JoinResponse)(nil),    // 5: agent.v1alpha1.JoinResponse
}
var file_agent_v1alpha1_agent_proto_depIdxs = []int32{
	0, // 0: agent.v1alpha1.StatusResponse.code:type_name -> agent.v1alpha1.StatusCode
	3, // 1: agent.v1alpha1.StatusResponse.kubelet:type_name -> agent.v1alpha1.ComponentStatus
	3, // 2: agent.v1alpha1.StatusResponse.containerd:type_name -> agent.v1alpha1.ComponentStatus
	0, // 3: agent.v1alpha1.JoinResponse.code:type_name -> agent.v1alpha1.StatusCode
	1, // 4: agent.v1alpha1.AgentService.Status:input_type -> agent.v1alpha1.StatusRequest
	4, // 5: agent.v1alpha1.AgentService.Join:input_type -> agent.v1alpha1.JoinRequest
	2, // 6: agent.v1alpha1.AgentService.Status:output_type -> agent.v1alpha1.StatusResponse
	5, // 7: agent.v1alpha1.AgentService.Join:output_type -> agent.v1alpha1.JoinResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_agent_v1alpha1_agent_proto_init() }
func file_agent_v1alpha1_agent_proto_init() {
	if File_agent_v1alpha1_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_v1alpha1_agent_proto_rawDesc), len(file_agent_v1alpha1_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_v1alpha1_agent_proto_goTypes,
		DependencyIndexes: file_agent_v1alpha1_agent_proto_depIdxs,
		EnumInfos:         file_agent_v1alpha1_agent_proto_enumTypes,
		MessageInfos:      file_agent_v1alpha1_agent_proto_msgTypes,
	}.Build()
	File_agent_v1alpha1_agent_proto = out.File
	file_agent_v1alpha1_agent_proto_goTypes = nil
	file_agent_v1alpha1_agent_proto_depIdxs = nil
}
