package controlplane

const (
	ConditionReady              ConditionType = "Ready"
	ConditionReconciling        ConditionType = "Reconciling"
	ConditionStalled            ConditionType = "Stalled"
	ConditionResourcesReady     ConditionType = "ResourcesReady"
	ConditionDeploymentReady    ConditionType = "DeploymentReady"
	ConditionWaitingForResource ConditionType = "WaitingForResource"

	ReasonDeploymentReady      ConditionReason = "DeploymentReady"
	ReasonDeploymentNotReady   ConditionReason = "DeploymentNotReady"
	ReasonWaitingForDeployment ConditionReason = "WaitingForDeployment"
	ReasonWaitingForService    ConditionReason = "WaitingForService"
	ReasonResourceCreated      ConditionReason = "ResourceCreated"
	ReasonResourceUpdated      ConditionReason = "ResourceUpdated"
	ReasonResourceNotReady     ConditionReason = "ResourceNotReady"
	ReasonAllResourcesReady    ConditionReason = "ResourcesReady"
	ReasonWaitingForResources  ConditionReason = "ResourcesNotReady"
	ReasonControlPlaneReady    ConditionReason = "ControlPlaneReady"

	MessageDeploymentReady                  ConditionMessage = "Deployment is ready"
	MessageDeploymentNotReady               ConditionMessage = "Deployment is not ready yet"
	MessageWaitingForDeployment             ConditionMessage = "Waiting for Deployment to become Ready"
	MessageWaitingForService                ConditionMessage = "Waiting for Service to be created"
	MessageAllResourcesReady                ConditionMessage = "All resources are Ready"
	MessageNotAllResourcesReady             ConditionMessage = "Some resources are not Ready"
	MessageWaitingForResources              ConditionMessage = "Waiting for resources to become Ready"
	MessageControlPlaneAllReady             ConditionMessage = "All control plane components are Ready"
	MessageWaitingForPKI                    ConditionMessage = "Waiting for ManagedPKI to become Ready"
	MessageWaitingForETCD                   ConditionMessage = "Waiting for ManagedETCD to become Ready"
	MessageWaitingForAPIServer              ConditionMessage = "Waiting for ManagedAPIServer to become Ready"
	MessageWaitingForControllerMgr          ConditionMessage = "Waiting for ManagedControllerManager to become Ready"
	MessageWaitingForScheduler              ConditionMessage = "Waiting for ManagedScheduler to become Ready"
	MessageAPIServerDeploymentReady         ConditionMessage = "kube-apiserver Deployment is Ready"
	MessageAPIServerWaitingForDeployment    ConditionMessage = "Waiting for kube-apiserver Deployment to become Ready"
	MessageControllerManagerDeploymentReady ConditionMessage = "kube-controller-manager Deployment is Ready"
	MessageControllerManagerWaiting         ConditionMessage = "Waiting for kube-controller-manager Deployment to become Ready"
	MessageSchedulerDeploymentReady         ConditionMessage = "kube-scheduler Deployment is Ready"
	MessageSchedulerWaiting                 ConditionMessage = "Waiting for kube-scheduler Deployment to become Ready"
	MessagePKIAllResourcesReady             ConditionMessage = "All PKI resources are Ready"
	MessagePKIWaitingResources              ConditionMessage = "Waiting for PKI resources to become Ready"
	MessageETCDAllResourcesReady            ConditionMessage = "etcd StatefulSet is Ready"
	MessageETCDWaitingResources             ConditionMessage = "Waiting for etcd StatefulSet to become Ready"
	MessageMCPAllReady                      ConditionMessage = "All control plane components are Ready"
	MessageMCPWaitingResources              ConditionMessage = "Waiting for control plane components to become Ready"
)
